export const projectData = [
  { id: 1,
    title: 'ZeroWasteCooking',
    description: 'This app helps people find recipes based on what they have at home to reduce food waste and facilitate meal planning. Logged in users can save recipes along with some notes, create a list of foods they have at home and a shopping list from saved recipes.',
    stack: ['JavaScript', 'React', 'Node.js', 'Express', 'MongoDB'],
    url:'',
    githubUrl: 'https://github.com/yukakoito/CB-Final-Project',
  },
  { id: 2,
    title: 'Weather app',
    description: '',
    stack: ['Typescript', 'React'],
    url:'',
    githubUrl: 'https://github.com/yukakoito/weather_app_with_typescript',
  },
];